### ISSUE TITLE
Assignment Complete

### ISSUE THREAD

**Issue by bluyam** [bluyam/yelp#1]
My submission is complete - though I didn't get to implement all the features I wanted. :-1: Please review! P.S. - I'm using my late day. :clock10: /cc @codepathreview

**Comment by codepathreview** [comment]
:+1: Great work! This primary challenge of this homework was to learn how to use AutoLayout to build adaptive UI's that work across many different screen sizes and orientations. If you haven't already, we recommend going back and running your homework again while rotating the device / simulator to ensure your AutoLayout constraints function as expected.

### Some small comments:
- Note that you should resolve all the Auto Layout constraint errors in your nibs.
- This alert is a little bit weird. What's the purpose of the second button?
  <img width="257" alt="screen shot 2016-02-08 at 10 05 54 pm" src="https://cloud.githubusercontent.com/assets/7917093/12889221/84a2176a-ceb0-11e5-9e25-346d8fb65935.png">
- Good job implementing `filters` page. But it would be better if you save the old user's choices.
- In Swift, you needn't call `break` at the end of each case.
- You can declare `var offsetAccumulator = 0` instead of `var offsetAccumulator: Int = 0`. The type is necessary if it is a `Double` or `Float`, etc.

Excellent submission overall as usual :wink: :confetti_ball: 

We have a detailed [Project 3 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_3_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

**Comment by codepathreview** [comment]
One more thing, `Implement map view of restaurant results` means you have to show the results as a map and pin the restaurant locations on that map.

**Comment by bluyam** [comment]
Thanks for the feedback! As far as the alert view goes, I didn't realize that the second button was there until I had to submit the assignment. :tired_face:
